### PR TITLE
Support Audi connect

### LINKED ISSUE #15: Support Audi Connect
I was just messing around with the Audi Connect API when I found this adapter. As it seems, both use the same API with some minor differences:

* The base part of the URL is `msg.audi.de` instead of `msg.volkswagen.de`.
* The initial `VWCarNet_Brand` is `"Audi"`.
* And some request headers are different:
    ```
    "X-App-ID": "de.audi.mmiapp",
	"X-App-Name": "MMIconnect",
	"X-App-Version": "2.8.3",
	"X-Brand": "audi",
    ```

If this is something you would like to support, I can provide a PR.

P.S.: Deutsch geht auch, ich bin nur gewöhnt auf GitHub englisch zu schreiben.

### LINKED ISSUE #188: Audi Connect
Related to #118, #164 

Python API is available at https://github.com/davidgiga1993/AudiAPI

I can test ("hardware" available :laughing: ).

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes: #15 
Fixes: https://github.com/ioBroker/AdapterRequests/issues/188

Untested, requires #17 to be merged

### CODE REVIEW

**Comment by AlCalzone** [comment]
I just verified - it works with my Audi

**Comment by AlCalzone** [comment]
@RPerkuhn If you need me to rebase #17 and this against your v0.3 branch, let me know.

**Comment by massa007** [comment]
@AlCalzone how can I use the adapter with my Audi? What do I need to change?

**Comment by massa007** [comment]
@AlCalzone could you implement your changes to your fork? I would like to use the adapter for Audi as well! But it seems that your Pull requests are not going to be merged :(

**Comment by AlCalzone** [comment]
@massa007 you can simply install the branch I'm trying to merge if you use `https://github.com/AlCalzone/ioBroker.vw-carnet/tarball/audi_connect` as the custom URL

**Comment by massa007** [comment]
@AlCalzone thanks for your answer! I managed to start your version as an instance in my ioBroker!
I don´t get any error message in the logs but the objects are still empty and the connection value is false...
I tried with a wrong username and get an error so I am sure my credentials are correct.
Any ideas?

**Comment by AlCalzone** [comment]
Might be because of #20

**Comment by massa007** [comment]
But is it still working for you?

**Comment by AlCalzone** [comment]
Honestly I haven't tested yet. I was experimenting primarily because of the remote heating which is not needed in summer. Too many other projects at the moment 😅

**Comment by Sneak-L8** [comment]
Actually it won't work due to change in athentification (Car-Net => We Connect)

**Comment by Buhu91** [comment]
Is it possible to support Skoda Connect, too? 
I installed the adapter, but it isn't working.

**Comment by massa007** [comment]
I was able to decrypt the API calls of the myAudi app via mitmproxy and an unlocked Android phone with xposed and a module to disable ssl pinning. Unfortunately I have just basic understanding of programming so if someone is interested I can provide my help!

> Honestly I haven't tested yet. I was experimenting primarily because of the remote heating which is not needed in summer. Too many other projects at the moment 😅

@AlCalzone Winter is coming ;)

**Comment by TA2k** [comment]
Hi @massa007  if you give me your proxy logs I can integrate audi in the iobroer vw connect adapter
https://github.com/TA2k/ioBroker.vw-connect

**Comment by AlCalzone** [comment]
closing in favor of vw-connect

**Pull request closed without merging**
